export { default as ButtonArrowIcon } from './button-arrow.svg';
export { default as ArrowRight } from './arrow-right.svg';
export { default as ArrowLeft } from './arrow-left.svg';
export { default as Medal } from './medal.svg';
export { default as ScanEye } from './scan-eye.svg';
export { default as SmartPhone } from './smartphone.svg';
export { default as TrendingDown } from './trending-down.svg';
export { default as PaintBucket } from './paint-bucket.svg';
export { default as CircleCheck } from './circle-check.svg';
export { default as X } from './x.svg';
export { default as PlayArrow } from './play-arrow.svg';  
export { default as GoolgeIcon} from './google.svg';
export { default as Clutch} from './clutch.svg';	
export { default as Goodfirm} from './goodfirm.svg';
export { default as Designrush} from './designrush.svg';
export { default as TopDevelopers } from './topdevelopers.svg';	
export { default as India } from  './india.svg'
export { default as UnitedStates } from './usa.svg';
export { default as Facebook } from './facebook.svg';
export { default as Dribble } from './dribble.svg';
export { default as LinkedIn } from './linkedIn.svg';
export { default as Twitter } from './twitter.svg';
export { default as YouTube } from './youtube.svg';
export { default as Pinterest } from './pinterest.svg';
export { default as Medium } from './medium.svg';
export { default as Instagram } from './instagram.svg';